#!/usr/bin/env python3

from nrpy import CodesDir, SpatialDimension, CoordSystem, Derivatives

if __name__ == '__main__':
    codesdir = CodesDir()
    spatial = SpatialDimension()
    coord_system = CoordSystem()
    derivatives = Derivatives(ccodesdir=codesdir)

    codesdir.build()
    spatial.build()
    derivatives.build_c_code_generation()
    coord_system.build_numerical_grid()
    derivatives.build_finite_difference_order()
